### ISSUE TITLE
WebContent ist unnötig. 

### ISSUE THREAD

**Issue by ArmaniS-Sys** [EnderKohle/BanSystem-v2#1]
https://github.com/EnderKohle/BanSystem-v2/tree/master/WebContent

Brauch man nicht, bei einem Bansystem was keine Webseite besitzt und ist somit Platz Verschwendung. Oder hab ich unrecht?

**Comment by EnderKohle** [comment]
War ein Ansatz aber wurde wieder verworfen und war zu Faul das aus Github rauszulöschen.
.
